# Generated by Django 3.1.2 on 2020-11-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('home', '0009_auto_20201023_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_greater_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
