# Generated by Django 3.1.2 on 2020-11-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('home', '0011_remove_todo_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
