# Generated by Django 3.1.2 on 2020-11-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201105_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='users',
            new_name='profile',
        ),
    ]
